version: '3.8'

services:
  # Define o serviço da sua aplicação Streamlit
  app:
    # Instrui o Compose a construir a imagem a partir do Dockerfile no diretório atual
    build: .
    # Define um nome amigável para o contêiner para fácil identificação
    container_name: appst
    # Mapeia a porta 8501 do seu computador (host) para a porta 8501 do contêiner
    ports:
      - "8501:8501"
    # Monta o diretório atual no diretório /app do contêiner.
    # Essencial para desenvolvimento, pois permite o live-reloading do Streamlit.
    volumes:
      - .:/app